export const EVENT_CAPACITY_DETAIL_VENDOR_LIST_RELOAD =
  'EVENT_CAPACITY_DETAIL_VENDOR_LIST_RELOAD';
export const EVENT_CAPACITY_DETAIL_TRUCK_LIST_RELOAD =
  'EVENT_CAPACITY_DETAIL_TRUCK_LIST_RELOAD';
export const EVENT_CAPACITY_DETAIL_RELOAD = 'EVENT_CAPACITY_DETAIL_RELOAD';
