export enum PermissionEnum {
  // Home Page 🚀🚀🚀 --start-- 🚀🚀🚀
  // HOME_PAGE = 'homePage',
  // BUSINESS_STATISTICS_SUMMARY = 'businessStatisticsSummary',
  // BUSINESS_PERFORMANCE = 'businessPerformance',
  // BUSINESS_PERFORMANCE_DOWNLOAD = 'businessSummaryDownload',
  // PERFORMANCE_COMPARISON = 'performanceComparison',
  // BUSINESS_RANKINGS = 'businessRankings',
  // NEW_CUSTOMERS = 'newCustomers',
  // Home Page 🚀🚀🚀 --end-- 🚀🚀🚀

  // Customer Management 🚀🚀🚀 --start-- 🚀🚀🚀
  CUSTOMER_MANAGEMENT = 'customerManagement',
  LEADS_POOL = 'leadsPool',
  CUSTOMERS_PAGE = 'customersPage',
  CUSTOMER_LIST = 'customerList',
  CUSTOMER_CONTRACT_TRACKING = 'customerContractTracking',
  CUSTOMER_CONTRACT_TRACKING_UPDATE = 'customerContractTrackingUpdate',
  CUSTOMER_STATISTICS = 'customerStatistics',
  CUSTOMER_LIST_CREATE = 'customerListCreate',
  CUSTOMER_LIST_EDIT = 'customerListEdit',
  CUSTOMER_LIST_TRANSFER = 'customerListTransfer',
  CUSTOMER_DETAIL = 'customerDetail',
  CUSTOMER_DETAIL_TRANSFER = 'customerDetailTransfer',
  CUSTOMER_DETAIL_CREATE_PROJECT = 'customerDetailCreateProject',
  CUSTOMER_DETAIL_EDIT = 'customerDetailEdit',

  CUSTOMER_DETAIL_CONTACTS = 'customerDetailContacts',
  CUSTOMER_DETAIL_CONTACTS_ADD = 'customerDetailContactsAdd',
  CUSTOMER_DETAIL_CONTACTS_EDIT = 'customerDetailContactsEdit',
  CUSTOMER_DETAIL_CONTACTS_DELETE = 'customerDetailContactsDelete',

  CUSTOMER_DETAIL_FOLLOW_UP_RECORDS = 'customerDetailFollowUpRecords',
  CUSTOMER_DETAIL_FOLLOW_UP_RECORDS_EDIT = 'customerDetailFollowUpRecordsEdit',

  CUSTOMER_DETAIL_OPPORTUNITIES = 'customerDetailOpportunities',
  CUSTOMER_DETAIL_OPPORTUNITIES_ADD = 'customerDetailOpportunitiesAdd',
  CUSTOMER_DETAIL_OPPORTUNITIES_DETAIL = 'customerDetailOpportunitiesDetail',

  CUSTOMER_DETAIL_PROJECTS = 'customerDetailProjects',
  CUSTOMER_DETAIL_PROJECTS_DETAIL = 'customerDetailProjectsDetail',

  CUSTOMER_DETAIL_BUSINESS_DOC = 'customerDetailBusinessDocuments',
  CUSTOMER_DETAIL_BUSINESS_DOC_EDIT = 'customerDetailBusinessDocumentEdit',
  CUSTOMER_DETAIL_FINANCIAL_DOC = 'customerDetailFinancialDocuments',
  CUSTOMER_DETAIL_FINANCIAL_DOC_EDIT = 'customerDetailFinancialDocumentEdit',

  CUSTOMER_DETAIL_SUMMARY = 'customerDetailSummary',
  CUSTOMER_DETAIL_SUMMARY_EDIT = 'customerDetailSummaryEdit',

  CUSTOMER_DETAIL_CONTRACTS = 'customerDetailContracts',
  CUSTOMER_DETAIL_CONTRACTS_VIEW = 'customerDetailContractsView',
  CUSTOMER_DETAIL_CONTRACTS_DOWNLOAD = 'customerDetailContractsDownload',
  CUSTOMER_DETAIL_CONTRACTS_HISTORY = 'customerDetailContractsHistory',
  // CUSTOMER_DETAIL_CONTRACTS_TERMINATE = 'customerDetailContractsTerminate',

  LEAD_POOL_CREATE = 'leadsPoolCreate',
  LEAD_POOL_TRANSFER = 'leadsPoolTransfer',
  LEAD_POOL_EDIT = 'leadsPoolEdit',
  LEAD_DETAIL = 'leadDetail',
  LEAD_DETAIL_OPPORTUNITIES = 'leadDetailOpportunities',
  LEAD_DETAIL_OPPORTUNITIES_ADD = 'leadDetailOpportunitiesAdd',
  LEAD_DETAIL_OPPORTUNITIES_DETAIL = 'leadDetailOpportunitiesDetail',

  OPPORTUNITY_LIST = 'opportunityList',
  OPPORTUNITY_LIST_CREATE = 'opportunityListCreate',
  OPPORTUNITY_DETAIL = 'opportunityDetail',
  OPPORTUNITY_DETAIL_EDIT = 'opportunityDetailEdit',
  OPPORTUNITY_DETAIL_ASSOCIATED_PROJECT = 'opportunityDetailAssociatedProject',
  OPPORTUNITY_LIST_FOLLOW_UP = 'opportunityListFollowUp',
  OPPORTUNITY_DETAIL_FOLLOW_UP = 'opportunityDetailFollowUp',
  OPPORTUNITY_DETAIL_CUSTOMER_EDIT = 'opportunityDetailCustomerEdit',

  // TODO add more
  // Customer Management 🚀🚀🚀 --end-- 🚀🚀🚀

  // Vendor Management 🚀🚀🚀 --start-- 🚀🚀🚀
  VENDOR_MANAGEMENT = 'vendorManagement',

  VENDORS_PAGE = 'vendorsPage',
  VENDOR_LIST = 'vendorList',
  VENDOR_CONTRACT_TRACKING = 'vendorContractTracking',
  VENDOR_CONTRACT_TRACKING_UPDATE = 'vendorContractTrackingUpdate',
  VENDOR_CREATE = 'vendorCreate',
  VENDOR_TRANSFER = 'vendorTransfer',
  VENDOR_DETAIL = 'vendorDetail',
  VENDOR_DETAIL_BLOCK_AND_UNBLOCK = 'vendorDetailBlockAndUnblock',
  VENDOR_DETAIL_TERMINATE = 'vendorDetailTerminate',
  VENDOR_DETAIL_REACCREDIT = 'vendorDetailReaccredit',
  VENDOR_DETAIL_TRANSFER = 'vendorDetailTransfer',
  VENDOR_DETAIL_ACCREDITATION_APPROVAL = 'vendorDetailAccreditationApproval',
  VENDOR_DETAIL_SUMMARY = 'vendorDetailSummary',
  VENDOR_DETAIL_SUMMARY_EDIT = 'vendorDetailSummaryEdit',
  VENDOR_DETAIL_CONTACTS = 'vendorDetailContacts',
  VENDOR_DETAIL_CONTACTS_ADD = 'vendorDetailContactsAdd',
  VENDOR_DETAIL_CONTACTS_EDIT = 'vendorDetailContactsEdit',
  VENDOR_DETAIL_CONTACTS_DELETE = 'vendorDetailContactsDelete',
  VENDOR_DETAIL_FOLLOW_UP_RECORDS = 'vendorDetailFollowUpRecords',
  VENDOR_DETAIL_FOLLOW_UP_RECORDS_EDIT = 'vendorDetailFollowUpRecordsEdit',
  VENDOR_DETAIL_TRUCK_LIST = 'vendorDetailTruckList',
  VENDOR_DETAIL_TRUCK_ADD = 'vendorDetailTruckAdd',
  VENDOR_DETAIL_TRUCK_DETAIL = 'vendorDetailTruckDetail',
  VENDOR_DETAIL_TRUCK_UNBIND = 'vendorDetailTruckUnbind',
  VENDOR_DETAIL_CREW_LIST = 'vendorDetailCrewList',
  VENDOR_DETAIL_CREW_ADD = 'vendorDetailCrewAdd',
  VENDOR_DETAIL_CREW_DETAIL = 'vendorDetailCrewDetail',
  VENDOR_DETAIL_CREW_UNBIND = 'vendorDetailCrewUnbind',
  VENDOR_DETAIL_PROJECT_LIST = 'vendorDetailProjectList',
  VENDOR_DETAIL_PROJECT_DETAIL = 'vendorDetailProjectDetail',
  VENDOR_DETAIL_ACCREDITATION = 'vendorDetailAccreditation',
  VENDOR_DETAIL_ACCREDITATION_EDIT = 'vendorDetailAccreditationEdit',
  VENDOR_DETAIL_APPLICATION = 'vendorDetailApplication',
  // VENDOR_DETAIL_APPLICATION_DETAIL = 'vendorDetailApplicationDetail',
  VENDOR_DETAIL_APPLICATION_REVIEW = 'vendorDetailApplicationReview',
  VENDOR_DETAIL_FINANCIAL_DOC = 'vendorDetailFinancialDocuments',
  VENDOR_DETAIL_FINANCIAL_DOC_EDIT = 'vendorDetailFinancialDocumentEdit',
  VENDOR_DETAIL_CONTRACTS = 'vendorDetailContracts',
  VENDOR_DETAIL_CONTRACTS_VIEW = 'vendorDetailContractsView',
  VENDOR_DETAIL_CONTRACTS_DOWNLOAD = 'vendorDetailContractsDownload',
  VENDOR_DETAIL_CONTRACTS_HISTORY = 'vendorDetailContractsHistory',
  VENDOR_DETAIL_EDIT = 'vendorDetailEdit',
  VENDOR_LIST_EDIT = 'vendorListEdit',
  VENDOR_LIST_UPDATE_ACCREDITATION = 'vendorListUpdateAccreditation',

  TRUCK_LIST = 'truckList',
  TRUCK_CREATE = 'truckCreate',
  TRUCK_DETAIL = 'truckDetail',
  TRUCK_LIST_UPDATE_ACCREDITATION = 'truckListUpdateAccreditation',
  TRUCK_DETAIL_DEACTIVATE = 'truckDetailDeactivate',
  TRUCK_DETAIL_ACTIVATE = 'truckDetailActivate',
  TRUCK_DETAIL_ATTRIBUTION = 'truckDetailAttribution',
  TRUCK_DETAIL_ATTRIBUTION_APPROVAL = 'truckDetailAccreditationApproval',
  TRUCK_DETAIL_EDIT = 'truckDetailEdit',
  TRUCK_DETAIL_ACCREDITATION = 'truckDetailAccreditation',
  TRUCK_DETAIL_ACCREDITATION_EDIT = 'truckDetailAccreditationEdit',
  TRUCK_DETAIL_APPLICATION = 'truckDetailApplication',
  // TRUCK_DETAIL_APPLICATION_DETAIL = 'truckDetailApplicationDetail',
  TRUCK_DETAIL_APPLICATION_REVIEW = 'truckDetailApplicationReview',

  CREW_LIST = 'crewList',
  CREW_CREATE = 'crewCreate',
  CREW_DETAIL = 'crewDetail',
  CREW_LIST_UPDATE_ACCREDITATION = 'crewListUpdateAccreditation',
  CREW_DETAIL_DEACTIVATE = 'crewDetailDeactivate',
  CREW_DETAIL_ACTIVATE = 'crewDetailActivate',
  CREW_DETAIL_BLOCK = 'crewDetailBlock',
  CREW_DETAIL_ATTRIBUTION = 'crewDetailAttribution',
  CREW_DETAIL_ATTRIBUTION_APPROVAL = 'crewDetailAccreditationApproval',
  CREW_DETAIL_EDIT = 'crewDetailEdit',
  CREW_DETAIL_ACCREDITATION = 'crewDetailAccreditation',
  CREW_DETAIL_ACCREDITATION_EDIT = 'crewDetailAccreditationEdit',
  CREW_DETAIL_APPLICATION = 'crewDetailApplication',
  // CREW_DETAIL_APPLICATION_DETAIL = 'crewDetailApplicationDetail',
  CREW_DETAIL_APPLICATION_REVIEW = 'crewDetailApplicationReview',
  APPLICATION_LIST = 'applicationList',
  // APPLICATION_LIST_DETAIL = 'applicationListDetail',
  APPLICATION_LIST_REVIEW = 'applicationListReview',
  // Vendor Management 🚀🚀🚀 --end-- 🚀🚀🚀

  // Project Management 🚀🚀🚀 --start-- 🚀🚀🚀
  PROJECT_MANAGEMENT = 'projectManagement',

  // Alarm Dashboard
  ALARM_DASHBOARD = 'alarmDashboard',
  ALARM_DASHBOARD_TASK_LIST = 'alarmDashboardTaskList',
  ALARM_DASHBOARD_STATISTICS = 'alarmDashboardStatistics',

  PROJECT_LIST = 'projectList',
  PROJECT_LIST_CREATE = 'projectListCreate',
  PROJECT_DETAIL = 'projectDetail',
  PROJECT_DETAIL_OPERATION_LOG = 'projectDetailOperationLog',
  PROJECT_DETAIL_CANCEL = 'projectDetailCancel',
  PROJECT_DETAIL_START = 'projectDetailStart',
  PROJECT_DETAIL_BATCH_PRICE_UPDATE = 'projectDetailBatchPriceUpdate',
  PROJECT_DETAIL_TERMINATED = 'projectDetailTerminated',
  PROJECT_DETAIL_COMPLETE = 'projectDetailComplete',
  PROJECT_DETAIL_CREATE_WAYBILL = 'projectDetailCreateWaybill',
  PROJECT_DETAIL_ASSIGN = 'projectDetailAssign',
  PROJECT_DETAIL_EDIT = 'projectDetailEdit',
  PROJECT_DETAIL_SUSPEND = 'projectDetailSuspend',
  PROJECT_DETAIL_RESUME = 'projectDetailResume',
  PROJECT_DETAIL_POD_CONFIGURATION = 'projectDetailPodConfiguration',
  PROJECT_DETAIL_SUBTASK_CONFIGURATION = 'projectDetailSubtaskConfiguration',
  PROJECT_DETAIL_WAYBILLS = 'projectDetailWaybills',
  PROJECT_DETAIL_WAYBILLS_COPY = 'projectDetailWaybillsCopy',
  PROJECT_DETAIL_WAYBILLS_EXPORT = 'projectDetailWaybillsExport',
  PROJECT_DETAIL_WAYBILLS_DETAIL = 'projectDetailWaybillsDetail',
  PROJECT_DETAIL_BUSINESS_DOCUMENTS = 'projectDetailBusinessDocuments',
  PROJECT_DETAIL_BUSINESS_DOCUMENTS_EDIT = 'projectDetailBusinessDocumentsEdit',
  PROJECT_DETAIL_ROUTE_LIBRARY = 'projectDetailRouteLibrary',
  PROJECT_DETAIL_ROUTE_LIBRARY_CREATE = 'projectDetailRouteLibraryCreate',
  PROJECT_DETAIL_ROUTE_LIBRARY_DETAILS = 'projectDetailRouteLibraryDetails',
  PROJECT_DETAIL_CAPACITY_POOL = 'projectDetailCapacityPool',
  PROJECT_DETAIL_CAPACITY_POOL_CREATE = 'projectDetailCapacityPoolCreate',
  PROJECT_DETAIL_CAPACITY_POOL_DETAIL = 'projectDetailCapacityPoolDetail',
  PROJECT_DETAIL_TEAM_MEMBERS = 'projectDetailTeamMembers',
  PROJECT_DETAIL_TEAM_MEMBERS_ADD = 'projectDetailTeamMembersAdd',
  PROJECT_DETAIL_TEAM_MEMBERS_DELETE = 'projectDetailTeamMembersDelete',
  // PROJECT_DETAIL_ADDITIONS_SETTINGS = 'projectDetailAdditionSettings',

  PROJECT_DETAIL_STOP_POINTS = 'projectDetailStopPoints',
  PROJECT_DETAIL_STOP_POINT_CREATE = 'projectDetailStopPointsCreate',
  PROJECT_DETAIL_STOP_POINT_EDIT = 'projectDetailStopPointsEdit',
  PROJECT_DETAIL_STOP_POINT_DELETE = 'projectDetailStopPointsDelete',
  PROJECT_DETAIL_CUSTOMER_CONTRACTS = 'projectDetailCustomerContracts',
  PROJECT_DETAIL_CUSTOMER_CONTRACTS_CREATE = 'projectDetailCustomerContractsCreate',
  PROJECT_DETAIL_CUSTOMER_CONTRACTS_VIEW = 'projectDetailCustomerContractsView',
  PROJECT_DETAIL_CUSTOMER_CONTRACTS_DOWNLOAD = 'projectDetailCustomerContractsDownload',
  PROJECT_DETAIL_CUSTOMER_CONTRACTS_HISTORY = 'projectDetailCustomerContractsHistory',
  PROJECT_DETAIL_CUSTOMER_CONTRACTS_REJECT = 'projectDetailCustomerContractsReject',
  PROJECT_DETAIL_CUSTOMER_CONTRACTS_PASS = 'projectDetailCustomerContractsPass',
  PROJECT_DETAIL_CUSTOMER_CONTRACTS_TERMINATE = 'projectDetailCustomerContractsTerminate',
  PROJECT_DETAIL_CUSTOMER_CONTRACTS_DELETE = 'projectDetailCustomerContractsDelete',
  PROJECT_DETAIL_VENDOR_CONTRACTS = 'projectDetailVendorContracts',
  PROJECT_DETAIL_VENDOR_CONTRACTS_CREATE = 'projectDetailVendorContractsCreate',
  PROJECT_DETAIL_VENDOR_CONTRACTS_VIEW = 'projectDetailVendorContractsView',
  PROJECT_DETAIL_VENDOR_CONTRACTS_DOWNLOAD = 'projectDetailVendorContractsDownload',
  PROJECT_DETAIL_VENDOR_CONTRACTS_HISTORY = 'projectDetailVendorContractsHistory',
  PROJECT_DETAIL_VENDOR_CONTRACTS_REJECT = 'projectDetailVendorContractsReject',
  PROJECT_DETAIL_VENDOR_CONTRACTS_PASS = 'projectDetailVendorContractsPass',
  PROJECT_DETAIL_VENDOR_CONTRACTS_TERMINATE = 'projectDetailVendorContractsTerminate',
  PROJECT_DETAIL_VENDOR_CONTRACTS_DELETE = 'projectDetailVendorContractsDelete',
  PROJECT_DETAIL_CUSTOMER_CODE_CONFIGURATION = 'projectDetailCustomerCodeConfiguration',

  // transmittal
  TRANSMITTAL = 'transmittal',
  TRANSMITTAL_CREATE = 'transmittalCreate',
  TRANSMITTAL_DETAIL = 'transmittalDetail',

  // Route Libraries
  ROUTE_LIBRARIES = 'routeLibraries',
  ROUTE_LIBRARY_CREATE = 'routeLibraryCreate',
  ROUTE_LIBRARY_DETAIL = 'routeLibraryDetail',
  ROUTE_LIBRARY_DETAIL_MILEAGE_RANGE = 'routeLibraryDetailMileageRange',
  ROUTE_LIBRARY_DETAIL_MANAGE_TRUCK_TYPE = 'routeLibraryDetailManageTruckType',
  ROUTE_LIBRARY_DETAIL_ADD_ROUTE = 'routeLibraryDetailAddRoute',
  ROUTE_LIBRARY_DETAIL_CUSTOMER_PRICING = 'routeLibraryDetailCustomerPricing',
  ROUTE_LIBRARY_DETAIL_CUSTOMER_PRICING_EDIT_INFO = 'routeLibraryDetailCustomerPricingEditInfo',
  ROUTE_LIBRARY_DETAIL_CUSTOMER_PRICING_SETTING = 'routeLibraryDetailCustomerPricingSetting',
  ROUTE_LIBRARY_DETAIL_CUSTOMER_PRICING_SYNC_FROM_SHEET = 'routeLibraryDetailCustomerPricingSyncFromSheet',
  ROUTE_LIBRARY_DETAIL_CUSTOMER_PRICING_MANAGE_SHEET = 'routeLibraryDetailCustomerPricingManageSheet',
  ROUTE_LIBRARY_DETAIL_VENDOR_PRICING = 'routeLibraryDetailVendorPricing',
  ROUTE_LIBRARY_DETAIL_VENDOR_PRICING_EDIT_INFO = 'routeLibraryDetailVendorPricingEditInfo',
  ROUTE_LIBRARY_DETAIL_VENDOR_PRICING_SETTING = 'routeLibraryDetailVendorPricingSetting',
  ROUTE_LIBRARY_DETAIL_VENDOR_PRICING_SYNC_FROM_SHEET = 'routeLibraryDetailVendorPricingSyncFromSheet',
  ROUTE_LIBRARY_DETAIL_VENDOR_PRICING_MANAGE_SHEET = 'routeLibraryDetailVendorPricingManageSheet',
  ROUTE_LIBRARY_DETAIL_EDIT = 'routeLibraryDetailEdit',

  // ROUTE_LIBRARY_DETAIL_ROUTES_TAB = 'routeLibraryDetailRoutesTab',

  ROUTE_LIBRARY_DETAIL_ROUTES = 'routeLibraryDetailRoutes',
  ROUTE_LIBRARY_DETAIL_CUSTOMER_PRICING_VERSION_TAB = 'routeLibraryDetailCustomerPricingVersionTab',
  ROUTE_LIBRARY_DETAIL_VENDOR_PRICING_VERSION_TAB = 'routeLibraryDetailVendorPricingVersionTab',
  ROUTE_LIBRARY_DETAIL_ROUTES_EDIT = 'routeLibraryDetailRoutesEdit',
  ROUTE_LIBRARY_DETAIL_ROUTES_REVOKE_OR_APPROVE = 'routeLibraryDetailRoutesRevokeOrApprove',
  ROUTE_LIBRARY_DETAIL_ROUTES_DELETE = 'routeLibraryDetailRoutesDelete',
  ROUTE_LIBRARY_DETAIL_PRICE_SUPER = 'routeLibraryDetailPriceSuper',

  // Capacity Pool
  CAPACITY_POOLS = 'capacityPools',
  CAPACITY_POOL_CREATE = 'capacityPoolCreate',
  CAPACITY_POOL_DETAIL = 'capacityPoolDetail',
  CAPACITY_POOL_DETAIL_EDIT_CAPACITY_POOL = 'capacityPoolDetailEditCapacity',
  CAPACITY_POOL_DETAIL_EDIT = 'capacityPoolDetailEdit',
  CAPACITY_POOL_DETAIL_TRUCK_LIST = 'capacityPoolDetailTruckList',
  CAPACITY_POOL_DETAIL_TRUCK_DETAIL = 'capacityPoolDetailTruckDetail',
  CAPACITY_POOL_DETAIL_TRUCK_REVOKE_OR_APPROVE = 'capacityPoolDetailTruckRevokeOrApprove',
  CAPACITY_POOL_DETAIL_CREW_LIST = 'capacityPoolDetailCrewList',
  CAPACITY_POOL_DETAIL_CREW_DETAIL = 'capacityPoolDetailCrewDetail',
  CAPACITY_POOL_DETAIL_CREW_REVOKE_OR_APPROVE = 'capacityPoolDetailCrewRevokeOrApprove',
  CAPACITY_POOL_DETAIL_VENDOR_LIST = 'capacityPoolDetailVendorList',
  CAPACITY_POOL_DETAIL_VENDOR_REVOKE_OR_APPROVE = 'capacityPoolDetailVendorRevokeOrApprove',
  CAPACITY_POOL_DETAIL_VENDOR_VIEW_PRICE_VERSION = 'capacityPoolDetailVendorViewPriceVersion',
  CAPACITY_POOL_DETAIL_VENDOR_CREATE = 'capacityPoolDetailVendorCreate',
  CAPACITY_POOL_DETAIL_VENDOR_DETAIL = 'capacityPoolDetailVendorDetail',

  // Claim Tickets
  CLAIM_TICKETS = 'claimTickets',
  CLAIM_REQUEST = 'ClaimRequest',
  CLAIM_REQUEST_Detail = 'ClaimRequestDetail',
  CLAIM_REQUEST_EDIT = 'ClaimRequestEdit',
  // Claim Ticket
  CLAIM_TICKET = 'claimTicket',

  // Claim Type --start
  CLAIM_TYPE_GPS = 'claimTypeGPS',
  CLAIM_TYPE_DDC_TRAINING_FEE = 'claimTypeDDCTrainingFee',
  CLAIM_TYPE_CREW_UNIFORM_CHARGES = 'claimTypeCrewUniformCharges',
  CLAIM_TYPE_INTELUCK_INSURANCE = 'claimTypeInteluckInsurance',
  CLAIM_TYPE_COUPON_FEES = 'claimTypeCouponFees',
  CLAIM_TYPE_STUFFING_FEE_CDC = 'claimTypeStuffingFeeCDC',
  CLAIM_TYPE_EQUIPMENT_FEE = 'claimTypeEquipmentFee',
  CLAIM_TYPE_MEDICAL_FEE = 'claimTypeMedicalFee',
  CLAIM_TYPE_DELIVERY_CLAIMS = 'claimTypeDeliveryClaims',
  CLAIM_TYPE_KPI_CLAIMS = 'claimTypeKPIClaims',
  CLAIM_TYPE_THEFT_INCIDENT = 'claimTypeTheftIncident',
  CLAIM_TYPE_OTHERS = 'claimTypeOthers',
  // Claim Type --end

  CLAIM_TICKET_CREATE = 'claimTicketCreate',
  CLAIM_TICKET_BATCH_CREATE = 'claimTicketBatchCreate',
  CLAIM_TICKET_EXPORT = 'claimTicketExport',
  CLAIM_TICKET_DETAIL = 'claimTicketDetail',
  CLAIM_TICKET_DETAIL_EDIT_TICKET_INFO = 'claimTicketDetailEditTicketInfo',
  CLAIM_TICKET_DETAIL_EDIT_OC_STATUS = 'claimTicketDetailEditOCStatus',
  CLAIM_TICKET_DETAIL_ADD_REMARK = 'claimTicketDetailAddRemark',
  CLAIM_TICKET_DETAIL_ADD_PROOF = 'claimTicketDetailAddProof',
  CLAIM_TICKET_DETAIL_CREATE_REFUND = 'claimTicketDetailCreateRefund',
  CLAIM_TICKET_DETAIL_CANCEL_TICKET = 'claimTicketDetailCancelTicket',
  CLAIM_TICKET_DETAIL_CONFIRM = 'claimTicketDetailConfirm',
  CLAIM_TICKET_DETAIL_OC_CONFIRM = 'claimTicketDetailOCConfirm',
  CLAIM_TICKET_DETAIL_ONGOING_VALIDATION = 'claimTicketDetailOngoingValidation',
  CLAIM_TICKET_DETAIL_VENDOR_DISPUTED = 'claimTicketDetailVendorDisputed',
  CLAIM_TICKET_DETAIL_COMPLETED = 'claimTicketDetailCompleted',
  CLAIM_TICKET_DETAIL_EXPORT_DM = 'claimTicketDetailExportDM',
  // Refund Ticket
  REFUND_TICKET = 'refundTicket',
  REFUND_TICKET_CREATE = 'refundTicketCreate',
  REFUND_TICKET_EXPORT = 'refundTicketExport',
  REFUND_TICKET_LINKED_CLAIM_TICKET_DETAIL = 'refundTicketLinkedClaimTicketDetail',
  REFUND_TICKET_DETAIL = 'refundTicketDetail',
  REFUND_TICKET_DETAIL_EDIT_TICKET_INFO = 'refundTicketDetailEditTicketInfo',
  REFUND_TICKET_DETAIL_EDIT_OC_STATUS = 'refundTicketDetailEditOCStatus',
  REFUND_TICKET_DETAIL_ADD_REMARK = 'refundTicketDetailAddRemark',
  REFUND_TICKET_DETAIL_ADD_PROOF = 'refundTicketDetailAddProof',
  REFUND_TICKET_DETAIL_CANCEL_TICKET = 'refundTicketDetailCancelTicket',
  REFUND_TICKET_DETAIL_CONFIRM = 'refundTicketDetailConfirm',
  REFUND_TICKET_DETAIL_OC_CONFIRM = 'refundTicketDetailOCConfirm',
  REFUND_TICKET_DETAIL_ONGOING_VALIDATION = 'refundTicketDetailOngoingValidation',
  REFUND_TICKET_DETAIL_COMPLETED = 'refundTicketDetailCompleted',

  // waybill 🚀🚀🚀 --start-- 🚀🚀🚀
  WAYBILL = 'waybill',
  CREATE_WAYBILL = 'createWaybill',
  BATCH_CREATE_WAYBILL = 'batchCreateWaybill',
  BATCH_SUBMIT_WAYBILL = 'batchSubmitWaybill',
  BATCH_START_WAYBILL = 'batchStartWaybill',
  UPDATE_WAYBILLS = 'updateWaybills',
  EXPORT_REV_COST = 'exportRevCost',
  COPY_WAYBILL = 'copyWaybill',
  EXPORT_WAYBILL = 'exportWaybill',
  WAYBILL_DETAIL = 'waybillDetail',

  STANDARD_WAYBILL_DETAIL = 'standardWaybillDetail',
  TEMPORARY_WAYBILL_DETAIL = 'temporaryWaybillDetail',

  // standardWaybill
  STANDARD_WAYBILL_OPERATE = 'standardWaybillOperationLog',
  STANDARD_WAYBILL_ABNORMAL = 'standardWaybillAbnormal',
  STANDARD_WAYBILL_CANCEL = 'standardWaybillCancel',
  STANDARD_WAYBILL_DELETE = 'standardWaybillDelete',
  STANDARD_WAYBILL_EDIT_CUSTOMER_CODE = 'standardWaybillEditCustomerCode',
  STANDARD_WAYBILL_PARTIAL_PAYMENT = 'standardWaybillPartialPayment',
  STANDARD_WAYBILL_PARTIAL_PAYMENT_EDIT = 'standardWaybillPartialPaymentEdit',
  STANDARD_WAYBILL_ADD_RECORD = 'standardWaybillAddRecord',
  STANDARD_WAYBILL_ADDITIONAL = 'standardWaybillAdditionalCharge',
  STANDARD_WAYBILL_ADDITIONAL_OBJECT_EDIT = 'standardWaybillAdditionalChargeEdit',
  STANDARD_WAYBILL_ADDITIONAL_STATUS_EDIT = 'standardWaybillAdditionalChargeStatusEdit',
  STANDARD_WAYBILL_CONFIRM_ROUTE = 'standardWaybillConfirmRoute',
  STANDARD_WAYBILL_MANAGE_POD = 'standardWaybillManagePOD',
  STANDARD_WAYBILL_SUBMIT = 'standardWaybillSubmit',
  STANDARD_WAYBILL_START = 'standardWaybillStart',
  // STANDARD_WAYBILL_CONFIRM_WAYBILL = 'standardWaybillConfirmWaybill',
  STANDARD_WAYBILL_TRACKS = 'standardWaybillTracks',
  STANDARD_WAYBILL_TRACKS_EDIT_POSITION = 'standardWaybillTracksEditPosition',
  STANDARD_WAYBILL_ROUTE = 'standardWaybillRoute',
  STANDARD_WAYBILL_ROUTE_PLANNING = 'standardWaybillRoutePlanning',
  STANDARD_WAYBILL_ROUTE_PLANNING_CREATE_STOP_POINT = 'standardWaybillRoutePlanningCreateStopPoint',
  STANDARD_WAYBILL_CARRIER = 'standardWaybillCarrier',
  STANDARD_WAYBILL_CARRIER_ASSIGN = 'standardWaybillCarrierAssign',
  STANDARD_WAYBILL_BILLING = 'standardWaybillBilling',
  STANDARD_WAYBILL_BILLING_EDIT = 'standardWaybillBillingEdit',
  STANDARD_WAYBILL_POD = 'standardWaybillPOD',
  STANDARD_WAYBILL_POD_EDIT = 'standardWaybillPODEdit',
  STANDARD_WAYBILL_BASIC_INFO = 'standardWaybillBasicInformation',
  STANDARD_WAYBILL_BASIC_INFO_EDIT = 'standardWaybillBasicInformationEdit',
  STANDARD_WAYBILL_REMARK = 'standardWaybillRemark',
  STANDARD_WAYBILL_REMARK_ADD = 'standardWaybillRemarkAdd',
  STANDARD_WAYBILL_REMARK_EDIT = 'standardWaybillRemarkEdit',
  STANDARD_WAYBILL_REMARK_DELETE = 'standardWaybillRemarkDelete',
  STANDARD_WAYBILL_EXCEPTION_FEE = 'standardWaybillExceptionFee',
  STANDARD_WAYBILL_EXCEPTION_FEE_OBJECT_EDIT = 'standardWaybillExceptionFeeObjectEdit',
  STANDARD_WAYBILL_EXCEPTION_FEE_STATUS_EDIT = 'standardWaybillExceptionFeeStatusEdit',
  STANDARD_WAYBILL_TRUCK_TYPE = 'standardWaybillTruckType',
  STANDARD_WAYBILL_LINKED_STATEMENT = 'standardWaybillLinkedStatement',
  STANDARD_WAYBILL_VIEW_AMOUNT = 'standardWaybillViewAmount',
  STANDARD_WAYBILL_SWITCH_STATE = 'standardWaybillSwitchState',
  STANDARD_WAYBILL_SWITCH_TO_VERIFIED = 'standardWaybillSwitchToVerified',
  STANDARD_WAYBILL_CLAIM = 'standardWaybillClaim', // claim
  STANDARD_WAYBILL_CLAIM_OBJECT_EDIT = 'standardWaybillClaimObjectEdit',
  STANDARD_WAYBILL_CLAIM_STATUS_EDIT = 'standardWaybillClaimStatusEdit',
  STANDARD_WAYBILL_CLAIM_VIEW_AMOUNT = 'standardWaybillClaimViewAmount',
  STANDARD_WAYBILL_CLAIM_LINKED_STATEMENT = 'standardWaybillClaimLinkedStatement',
  STANDARD_WAYBILL_CLAIM_LINKED_TICKET = 'standardWaybillClaimLinkedTicket',
  STANDARD_WAYBILL_CLAIM_CREATE_TICKET = 'standardWaybillClaimCreateTicket',
  STANDARD_WAYBILL_REIMBURSEMENT = 'standardWaybillReimbursement', // Reimbursement Expense
  STANDARD_WAYBILL_REIMBURSEMENT_OBJECT_EDIT = 'standardWaybillReimbursementObjectEdit',
  STANDARD_WAYBILL_REIMBURSEMENT_STATUS_EDIT = 'standardWaybillReimbursementStatusEdit',
  STANDARD_WAYBILL_REIMBURSEMENT_VIEW_AMOUNT = 'standardWaybillReimbursementViewAmount',
  STANDARD_WAYBILL_REIMBURSEMENT_LINKED_STATEMENT = 'standardWaybillReimbursementLinkedStatement',
  STANDARD_WAYBILL_EXPORT_VIEW_AMOUNT = 'standardWaybillExportViewAmount',

  // temporaryWaybill
  TEMPORARY_WAYBILL_OPERATE = 'temporaryWaybillOperationLog',
  TEMPORARY_WAYBILL_ABNORMAL = 'temporaryWaybillAbnormal',
  TEMPORARY_WAYBILL_CANCEL = 'temporaryWaybillCancel',
  TEMPORARY_WAYBILL_DELETE = 'temporaryWaybillDelete',
  TEMPORARY_WAYBILL_EDIT_CUSTOMER_CODE = 'temporaryWaybillEditCustomerCode',
  TEMPORARY_WAYBILL_PARTIAL_PAYMENT = 'temporaryWaybillPartialPayment',
  TEMPORARY_WAYBILL_PARTIAL_PAYMENT_EDIT = 'temporaryWaybillPartialPaymentEdit',
  TEMPORARY_WAYBILL_ADD_RECORD = 'temporaryWaybillAddRecord',
  TEMPORARY_WAYBILL_ADDITIONAL = 'temporaryWaybillAdditionalCharge',
  TEMPORARY_WAYBILL_ADDITIONAL_OBJECT_EDIT = 'temporaryWaybillAdditionalChargeEdit',
  TEMPORARY_WAYBILL_ADDITIONAL_STATUS_EDIT = 'temporaryWaybillAdditionalChargeStatusEdit',
  TEMPORARY_WAYBILL_CONFIRM_ROUTE = 'temporaryWaybillConfirmRoute',
  TEMPORARY_WAYBILL_MANAGE_POD = 'temporaryWaybillManagePOD',
  TEMPORARY_WAYBILL_SUBMIT = 'temporaryWaybillSubmit',
  TEMPORARY_WAYBILL_START = 'temporaryWaybillStart',
  // TEMPORARY_WAYBILL_CONFIRM_WAYBILL = 'temporaryWaybillConfirmWaybill',
  TEMPORARY_WAYBILL_TRACKS = 'temporaryWaybillTracks',
  TEMPORARY_WAYBILL_TRACKS_EDIT_POSITION = 'temporaryWaybillTracksEditPosition',
  TEMPORARY_WAYBILL_ROUTE = 'temporaryWaybillRoute',
  TEMPORARY_WAYBILL_ROUTE_PLANNING = 'temporaryWaybillRoutePlanning',
  TEMPORARY_WAYBILL_ROUTE_PLANNING_CREATE_STOP_POINT = 'temporaryWaybillRoutePlanningCreateStopPoint',
  TEMPORARY_WAYBILL_CARRIER = 'temporaryWaybillCarrier',
  TEMPORARY_WAYBILL_CARRIER_ASSIGN = 'temporaryWaybillCarrierAssign',
  TEMPORARY_WAYBILL_BILLING = 'temporaryWaybillBilling',
  TEMPORARY_WAYBILL_BILLING_EDIT = 'temporaryWaybillBillingEdit',
  TEMPORARY_WAYBILL_POD = 'temporaryWaybillPOD',
  TEMPORARY_WAYBILL_POD_EDIT = 'temporaryWaybillPODEdit',
  TEMPORARY_WAYBILL_BASIC_INFO = 'temporaryWaybillBasicInformation',
  TEMPORARY_WAYBILL_BASIC_INFO_EDIT = 'temporaryWaybillBasicInformationEdit',
  TEMPORARY_WAYBILL_REMARK = 'temporaryWaybillRemark',
  TEMPORARY_WAYBILL_REMARK_ADD = 'temporaryWaybillRemarkAdd',
  TEMPORARY_WAYBILL_REMARK_EDIT = 'temporaryWaybillRemarkEdit',
  TEMPORARY_WAYBILL_REMARK_DELETE = 'temporaryWaybillRemarkDelete',
  TEMPORARY_WAYBILL_EXCEPTION_FEE = 'temporaryWaybillExceptionFee',
  TEMPORARY_WAYBILL_EXCEPTION_FEE_OBJECT_EDIT = 'temporaryWaybillExceptionFeeObjectEdit',
  TEMPORARY_WAYBILL_EXCEPTION_FEE_STATUS_EDIT = 'temporaryWaybillExceptionFeeStatusEdit',
  TEMPORARY_WAYBILL_TRUCK_TYPE = 'temporaryWaybillTruckType',
  TEMPORARY_WAYBILL_LINKED_STATEMENT = 'temporaryWaybillLinkedStatement',
  TEMPORARY_WAYBILL_VIEW_AMOUNT = 'temporaryWaybillViewAmount',
  TEMPORARY_WAYBILL_SWITCH_STATE = 'temporaryWaybillSwitchState',
  TEMPORARY_WAYBILL_SWITCH_TO_VERIFIED = 'temporaryWaybillSwitchToVerified',
  TEMPORARY_WAYBILL_CLAIM = 'temporaryWaybillClaim', // claim
  TEMPORARY_WAYBILL_CLAIM_OBJECT_EDIT = 'temporaryWaybillClaimObjectEdit',
  TEMPORARY_WAYBILL_CLAIM_STATUS_EDIT = 'temporaryWaybillClaimStatusEdit',
  TEMPORARY_WAYBILL_CLAIM_VIEW_AMOUNT = 'temporaryWaybillClaimViewAmount',
  TEMPORARY_WAYBILL_CLAIM_LINKED_STATEMENT = 'temporaryWaybillClaimLinkedStatement',
  TEMPORARY_WAYBILL_CLAIM_LINKED_TICKET = 'temporaryWaybillClaimLinkedTicket',
  TEMPORARY_WAYBILL_CLAIM_CREATE_TICKET = 'temporaryWaybillClaimCreateTicket',
  TEMPORARY_WAYBILL_REIMBURSEMENT = 'temporaryWaybillReimbursement', // Reimbursement Expense
  TEMPORARY_WAYBILL_REIMBURSEMENT_OBJECT_EDIT = 'temporaryWaybillReimbursementObjectEdit',
  TEMPORARY_WAYBILL_REIMBURSEMENT_STATUS_EDIT = 'temporaryWaybillReimbursementStatusEdit',
  TEMPORARY_WAYBILL_REIMBURSEMENT_VIEW_AMOUNT = 'temporaryWaybillReimbursementViewAmount',
  TEMPORARY_WAYBILL_REIMBURSEMENT_LINKED_STATEMENT = 'temporaryWaybillReimbursementLinkedStatement',
  TEMPORARY_WAYBILL_EXPORT_VIEW_AMOUNT = 'temporaryWaybillExportViewAmount',
  //Financial
  WAYBILL_REJECT_PRICE = 'waybillRejectPrice',
  WAYBILL_REJECT_WAYBILL_INFORMATION = 'waybillRejectWaybillInformation',
  WAYBILL_CONFIRM_POD_RECEIPT = 'waybillConfirmPODReceipt',
  WAYBILL_CONFIRM_VERIFICATION = 'waybillConfirmVerification',
  WAYBILL_CONFIRM_PRICE = 'waybillConfirmPrice',

  // waybill 🚀🚀🚀 --end-- 🚀🚀🚀

  // subtask
  SUBTASK = 'subtask',
  SUBTASK_CREATE = 'subtaskCreate',
  SUBTASK_DETAIL = 'subtaskDetail',
  SUBTASK_REMIND = 'subtaskRemind',
  // Project Management 🚀🚀🚀 --end-- 🚀🚀🚀

  // User Mgmt
  USER_MANAGEMENT = 'userManagement',
  VENDOR_ACCOUNT_LIST = 'vendorAccountList',
  CUSTOMER_ACCOUNT_LIST = 'customerAccountList',

  //

  STATISTICS = 'statistics',
  DASHBOARD_BOOKING = 'dashboardBooking',
  CUSTOMER_ANALYSIS = 'customerAnalysis',
  VENDOR_ANALYSIS = 'vendorAnalysis',
  DASHBOARD_KPI = 'dashboardKpi',
  SUB_DASHBOARD = 'subDashboard',
  ADOPTION_DASHBOARD = 'adoptionDashboard',
  FIELD_SALES_MAP = 'fieldSalesMap',
  MONTHLY_DELIVERED_PANEL = 'monthlyDeliveredPanel',
  // Tools
  TOOLS = 'tools',
  WATERMARK = 'watermark',
  ELECTRONIC_SIGNATURE = 'electronicSignature',
  CONTRACT_MANAGEMENT = 'contractManagement',
  CONTRACT_MANAGEMENT_CREATE = 'contractManagementCreateContract',
  CONTRACT_MANAGEMENT_VIEW = 'contractManagementViewContract',
  CONTRACT_MANAGEMENT_DOWNLOAD = 'contractManagementDownloadContract',
  CONTRACT_MANAGEMENT_HISTORY = 'contractManagementHistory',
  CONTRACT_MANAGEMENT_REJECT = 'contractManagementRejectContract',
  CONTRACT_MANAGEMENT_PASS = 'contractManagementPassContract',
  CONTRACT_MANAGEMENT_DELETE = 'contractManagementDeleteContract',
  CONTRACT_MANAGEMENT_TERMINATE = 'contractManagementTerminateContract',
  WAYBILL_AUTOMATION = 'waybillAutomationPage',
  WAYBILL_AUTOMATION_OPERATION_SHOPEE_FLASH = 'waybillAutomationOperationShopeeFlash',
  WAYBILL_AUTOMATION_OPERATION_SHOPPE_LAST_MILE = 'waybillAutomationOperationShoppeLastMile',
  CONVERSION_TOOL = 'conversionTool',
  SLACK_GROUP_MESSAGE = 'slackGroupMessage',
  DATA_PROCESSING = 'dataProcessing',
  FA_BILLING_RECORDS = 'faBillingRecords',
  PRICE_INQUIRY_TOOL = 'priceInquiryTool',
  PRICING_CHECK = 'pricingCheck',
  PRICING_CHECK_BATCH_CONFIRM_PRICE = 'batchConfirmPrice',

  // Permission Management 🚀🚀🚀 --start-- 🚀🚀🚀
  PERMISSION_MANAGEMENT = 'permissionManagement',
  ACCOUNT_MANAGEMENT = 'accountManagement',
  ORGANIZATION_MANAGEMENT = 'organizationManagement',
  ROLE_TEMPLATE = 'roleTemplate',
  // Permission Management 🚀🚀🚀 --end-- 🚀🚀🚀

  // Billing Mgmt
  BILLING_MANAGEMENT = 'billingManagement',
  //customer
  AR_STATEMENT_STATISTIC = 'arStatementStatistic',
  AR_STATEMENT_STATISTIC_OVERVIEW = 'arStatementStatisticOverview',
  AR_STATEMENT_STATISTIC_OVERVIEW_DOWNLOAD = 'arStatementStatisticOverviewDownload',
  AR_STATEMENT_STATISTIC_BREAKDOWN_BY_MONTH = 'arStatementStatisticBreakdownByMonth',
  AR_STATEMENT_STATISTIC_BREAKDOWN_BY_MONTH_DOWNLOAD = 'arStatementStatisticBreakdownByMonthDownload',
  AR_STATEMENT_STATISTIC_UN_BILLED_BREAKDOWN_BY_CUSTOMER = 'arStatementStatisticUnBilledBreakdownByCustomer',
  AR_STATEMENT_STATISTIC_UN_BILLED_BREAKDOWN_BY_CUSTOMER_DOWNLOAD = 'arStatementStatisticUnBilledBreakdownByCustomerDownload',
  AR_STATEMENT_STATISTIC_UN_COLLECTED_BREAKDOWN_BY_CUSTOMER = 'arStatementStatisticUnCollectedBreakdownByCustomer',
  AR_STATEMENT_STATISTIC_UN_COLLECTED_BREAKDOWN_BY_CUSTOMER_DOWNLOAD = 'arStatementStatisticUnCollectedBreakdownByCustomerDownload',
  CUSTOMER_STATEMENT = 'customerStatement',
  CUSTOMER_STATEMENT_ADD = 'customerStatementAdd',
  CUSTOMER_STATEMENT_EXPORT = 'customerStatementExport',
  CUSTOMER_STATEMENT_DETAIL = 'customerStatementDetail',
  CUSTOMER_STATEMENT_DETAIL_BILLING = 'customerStatementDetailBilling',
  CUSTOMER_STATEMENT_DETAIL_BILLING_EDIT_CHARGE = 'customerStatementDetailBillingEditCharge',
  CUSTOMER_STATEMENT_DETAIL_BILLING_EDIT_CHARGE_HISTORY = 'customerStatementDetailBillingEditChargeHistory',
  CUSTOMER_STATEMENT_DETAIL_BILLING_IS_TAX_INCLUSIVE = 'customerStatementDetailBillingIsTaxInclusive',
  CUSTOMER_STATEMENT_DETAIL_BILLING_ADDITIONAL_CHARGE = 'customerStatementDetailBillingAdditionalCharge',

  CUSTOMER_STATEMENT_DETAIL_BILLING_CLAIM_TICKET_DETAIL = 'customerStatementDetailBillingClaimTicketDetail',
  CUSTOMER_STATEMENT_DETAIL_BILLING_CLAIM_TICKET_DETAIL_ADD = 'customerStatementDetailBillingClaimTicketDetailAdd',
  CUSTOMER_STATEMENT_DETAIL_BILLING_CLAIM_TICKET_DETAIL_REMOVE = 'customerStatementDetailBillingClaimTicketDetailRemove',
  CUSTOMER_STATEMENT_DETAIL_BILLING_CREATE_CLAIM_REQUEST = 'customerStatementDetailBillingCreateClaimRequest',

  CUSTOMER_STATEMENT_DETAIL_COLLECTION = 'customerStatementDetailCollection',
  CUSTOMER_STATEMENT_DETAIL_COLLECTION_ADD = 'customerStatementDetailCollectionAdd',
  CUSTOMER_STATEMENT_DETAIL_INVOICE = 'customerStatementDetailInvoice',
  CUSTOMER_STATEMENT_DETAIL_INVOICE_ADD = 'customerStatementDetailInvoiceAdd',
  CUSTOMER_STATEMENT_DETAIL_PROOF = 'customerStatementDetailProof',
  CUSTOMER_STATEMENT_DETAIL_PROOF_ADD = 'customerStatementDetailProofAdd',
  CUSTOMER_STATEMENT_DETAIL_WAYBILL = 'customerStatementDetailWaybill',
  // CUSTOMER_STATEMENT_DETAIL_WAYBILL_EDIT_CHARGE = 'customerStatementDetailWaybillEditCharge',
  CUSTOMER_STATEMENT_DETAIL_ASSOCIATED_WAYBILL = 'customerStatementDetailAssociatedWaybill',
  // CUSTOMER_STATEMENT_DETAIL_WAYBILL_EDIT_CHARGE_HISTORY = 'customerStatementDetailWaybillEditChargeHistory',
  CUSTOMER_STATEMENT_DETAIL_WAYBILL_EDIT_TAX_RATE = 'customerStatementDetailWaybillEditTaxRate',

  CUSTOMER_STATEMENT_DETAIL_WAYBILL_EDIT_INVOICE = 'customerStatementDetailWaybillEditInvoice',
  CUSTOMER_STATEMENT_DETAIL_WAYBILL_FILL_IN_ALL_INVOICE = 'customerStatementDetailWaybillFillInAllInvoice',
  CUSTOMER_STATEMENT_DETAIL_WAYBILL_BILLED_AMOUNT = 'customerStatementDetailWaybillBilledAmount',
  CUSTOMER_STATEMENT_DETAIL_WAYBILL_BILLED_AMOUNT_EDIT = 'customerStatementDetailWaybillBilledAmountEdit',
  CUSTOMER_STATEMENT_DETAIL_WAYBILL_EDIT_REIMBURSEMENT_EXPENSE = 'customerStatementDetailWaybillEditReimbursementExpense',

  CUSTOMER_STATEMENT_DETAIL_CONFIRM = 'customerStatementDetailConfirm',
  CUSTOMER_STATEMENT_DETAIL_CUSTOMER_CONFIRM = 'customerStatementDetailCustomerConfirm',
  CUSTOMER_STATEMENT_DETAIL_CONFIRM_COLLECTED = 'customerStatementDetailConfirmCollected',
  CUSTOMER_STATEMENT_DETAIL_EXPORT_STATEMENT = 'customerStatementDetailExportStatement',
  CUSTOMER_STATEMENT_DETAIL_WRITE_OFF = 'customerStatementDetailWriteOff',
  CUSTOMER_STATEMENT_DETAIL_CANCEL = 'customerStatementDetailCancel',
  CUSTOMER_STATEMENT_DETAIL_REJECT = 'customerStatementDetailReject',
  CUSTOMER_STATEMENT_DETAIL_EXPORT_RECORD = 'customerStatementDetailExportRecord',

  //vendor
  VENDOR_STATEMENT = 'vendorStatement',
  VENDOR_STATEMENT_ADD = 'vendorStatementAdd',
  VENDOR_STATEMENT_EXPORT = 'vendorStatementExport',
  VENDOR_STATEMENT_DETAIL = 'vendorStatementDetail',
  VENDOR_STATEMENT_DETAIL_BILLING = 'vendorStatementDetailBilling',
  VENDOR_STATEMENT_DETAIL_BILLING_EDIT_CHARGE = 'vendorStatementDetailBillingEditCharge',
  VENDOR_STATEMENT_DETAIL_BILLING_EDIT_CHARGE_HISTORY = 'vendorStatementDetailBillingEditChargeHistory',
  VENDOR_STATEMENT_DETAIL_BILLING_ADDITIONAL_CHARGE = 'vendorStatementDetailBillingAdditionalCharge',
  VENDOR_STATEMENT_DETAIL_BILLING_IS_TAX_INCLUSIVE = 'vendorStatementDetailBillingIsTaxInclusive',
  VENDOR_STATEMENT_DETAIL_BILLING_CLAIM_TICKET_DETAIL = 'vendorStatementDetailBillingClaimTicketDetail',
  VENDOR_STATEMENT_DETAIL_BILLING_CLAIM_TICKET_DETAIL_ADD = 'vendorStatementDetailBillingClaimTicketDetailAdd',
  VENDOR_STATEMENT_DETAIL_BILLING_CLAIM_TICKET_DETAIL_REMOVE = 'vendorStatementDetailBillingClaimTicketDetailRemove',
  VENDOR_STATEMENT_DETAIL_BILLING_CREATE_CLAIM_REQUEST = 'vendorStatementDetailBillingCreateClaimRequest',

  VENDOR_STATEMENT_DETAIL_PAYMENT = 'vendorStatementDetailPayment',
  VENDOR_STATEMENT_DETAIL_PAYMENT_ADD = 'vendorStatementDetailPaymentAdd',
  VENDOR_STATEMENT_DETAIL_INVOICE = 'vendorStatementDetailInvoice',
  VENDOR_STATEMENT_DETAIL_INVOICE_Add = 'vendorStatementDetailInvoiceAdd',
  VENDOR_STATEMENT_DETAIL_PROOF = 'vendorStatementDetailProof',
  VENDOR_STATEMENT_DETAIL_PROOF_ADD = 'vendorStatementDetailProofAdd',
  VENDOR_STATEMENT_DETAIL_WAYBILL = 'vendorStatementDetailWaybill',
  VENDOR_STATEMENT_DETAIL_ASSOCIATED_WAYBILL = 'vendorStatementDetailAssociatedWaybill',
  VENDOR_STATEMENT_DETAIL_WAYBILL_EDIT_INVOICE = 'vendorStatementDetailWaybillEditInvoice',
  VENDOR_STATEMENT_DETAIL_WAYBILL_FILL_IN_ALL_INVOICE = 'vendorStatementDetailWaybillFillInAllInvoice',
  VENDOR_STATEMENT_DETAIL_WAYBILL_BILLED_AMOUNT = 'vendorStatementDetailWaybillBilledAmount',
  VENDOR_STATEMENT_DETAIL_WAYBILL_BILLED_AMOUNT_EDIT = 'vendorStatementDetailWaybillBilledAmountEdit',
  VENDOR_STATEMENT_DETAIL_WAYBILL_EDIT_TAX_RATE = 'vendorStatementDetailWaybillEditTaxRate',
  VENDOR_STATEMENT_DETAIL_WAYBILL_EDIT_REIMBURSEMENT_EXPENSE = 'vendorStatementDetailWaybillEditReimbursementExpense',

  VENDOR_STATEMENT_DETAIL_CONFIRM = 'vendorStatementDetailConfirm',
  VENDOR_STATEMENT_DETAIL_VENDOR_CONFIRM = 'vendorStatementDetailVendorConfirm',
  VENDOR_STATEMENT_DETAIL_CONFIRM_PAID = 'vendorStatementDetailConfirmPaid',
  VENDOR_STATEMENT_DETAIL_EXPORT_STATEMENT = 'vendorStatementDetailExportStatement',
  VENDOR_STATEMENT_DETAIL_WRITE_OFF = 'vendorStatementDetailWriteOff',
  VENDOR_STATEMENT_DETAIL_CANCEL = 'vendorStatementDetailCancel',
  VENDOR_STATEMENT_DETAIL_REJECT = 'vendorStatementDetailReject',
  VENDOR_STATEMENT_DETAIL_EXPORT_RECORD = 'vendorStatementDetailExportRecord',

  TAX_RATE_SETTING = 'taxRateSetting',
  TAX_RATE_SETTING_EDIT = 'taxRateSettingEdit',
}
