export const EVENT_SUBTASK_LIST_RELOAD = 'EVENT_SUBTASK_LIST_RELOAD';
export const EVENT_SUBTASK_DETAIL_RELOAD = 'EVENT_SUBTASK_DETAIL_RELOAD';
export const EVENT_SUBTASK_DRAWER_LOADING = 'EVENT_SUBTASK_DRAWER_LOADING';
