export const EVENT_PROOF_LIST_RELOAD = 'EVENT_PROOF_LIST_RELOAD';
export const EVENT_INVOICE_LIST_RELOAD = 'EVENT_INVOICE_LIST_RELOAD';
export const EVENT_BILLING_STATEMENT_DETAIL_RELOAD =
  'EVENT_BILLING_STATEMENT_DETAIL_RELOAD';
export const EVENT_BILLING_STATEMENT_WAYBILL_EDIT_STATUS =
  'EVENT_BILLING_STATEMENT_WAYBILL_EDIT_STATUS';
export const EVENT_BILLING_STATEMENT_WAYBILL_RELOAD =
  'EVENT_BILLING_STATEMENT_WAYBILL_RELOAD';
export const EVENT_BILLING_STATEMENT_WAYBILL_INVOICE_RELOAD =
  'EVENT_BILLING_STATEMENT_WAYBILL_INVOICE_RELOAD';
export const EVENT_BILLING_STATEMENT_WAYBILL_PROOF_CHECK_ID =
  'EVENT_BILLING_STATEMENT_WAYBILL_PROOF_CHECK_ID';
export const EVENT_BILLING_STATEMENT_WAYBILL_BILLED_AMOUNT_RELOAD =
  'EVENT_BILLING_STATEMENT_WAYBILL_BILLED_AMOUNT_RELOAD';
