import { SignTypeEnum } from '@/constants';
import { IToolField } from './interface';

export const defaultToolFieldList: IToolField[] = [
  {
    signType: SignTypeEnum.SIGNATURE,
    signTypeName: 'Signature',
    required: true,
    width: 125,
    height: 50,
    // minWidth: 10,
    // minHeight: 4,
    // maxWidth: 200,
    // maxHeight: 100,
    font: 'Arial',
    fontSize: 20,
  },
  {
    signType: SignTypeEnum.DATE,
    signTypeName: 'Date',
    required: false,
    width: 110,
    height: 18,
    // minWidth: 10,
    // minHeight: 4,
    // maxWidth: 200,
    // maxHeight: 100,
    font: 'Arial',
    fontSize: 14,
  },
  {
    signType: SignTypeEnum.TEXT,
    signTypeName: 'Text',
    required: false,
    width: 110,
    height: 18,
    // minWidth: 10,
    // minHeight: 4,
    // maxWidth: 200,
    // maxHeight: 100,
    font: 'Arial',
    fontSize: 14,
  },
  {
    signType: SignTypeEnum.COMPANY,
    signTypeName: 'Company',
    required: false,
    width: 110,
    height: 18,
    // minWidth: 10,
    // minHeight: 4,
    // maxWidth: 200,
    // maxHeight: 100,
    font: 'Arial',
    fontSize: 14,
  },
  {
    signType: SignTypeEnum.ADDRESS,
    signTypeName: 'Address',
    required: false,
    width: 110,
    height: 18,
    // minWidth: 10,
    // minHeight: 4,
    // maxWidth: 200,
    // maxHeight: 100,
    font: 'Arial',
    fontSize: 14,
  },
  {
    signType: SignTypeEnum.EMAIL,
    signTypeName: 'Email',
    required: false,
    width: 110,
    height: 18,
    // minWidth: 10,
    // minHeight: 4,
    // maxWidth: 200,
    // maxHeight: 100,
    font: 'Arial',
    fontSize: 14,
  },
];

export const resizeHandleClasses = {
  top: 'touch-node hidden',
  left: 'touch-node hidden',
  right: 'touch-node hidden',
  bottom: 'touch-node hidden',
  topLeft: 'touch-node',
  topRight: 'touch-node',
  bottomLeft: 'touch-node',
  bottomRight: 'touch-node',
};

export { SignTypeEnum };
