export const EVENT_WAYBILL_POD_LIST_RELOAD = 'EVENT_WAYBILL_POD_LIST_RELOAD';
export const EVENT_WAYBILL_REMARK_LIST_RELOAD =
  'EVENT_WAYBILL_REMARK_LIST_RELOAD';
export const EVENT_WAYBILL_ADD_RECORD = 'EVENT_WAYBILL_ADD_RECORD';
